repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # Latest stable version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        additional_dependencies: ['importlib-metadata==4.13.0']
        args:
          - --config=.flake8  # Explicitly tell pre-commit to use the .flake8 config

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.4
    hooks:
      - id: autopep8
        args:
          - --in-place
          - --aggressive  # First level of aggressiveness
          - --aggressive  # Increase aggressiveness
          - --max-line-length=88  # Ensure the max line length is 88


  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3
        args:
          - --line-length=88
