[tool.black]
line-length = 88
target-version = ['py39']
exclude = '\.git|\.tox|\.venv|build|lib|dist|_build|\.mypy_cache|venv'

[tool.flake8]
max-line-length = 88
exclude = ".git,__pycache__,build,dist,venv,.venv,*.egg-info,venv/*,.venv/*"


[tool.isort]
profile = "black"
