"""Add open, high, low, close, and volume columns to stocks

Revision ID: 184a1c26dc16
Revises: d74fcf8c0b1e
Create Date: 2024-09-28 23:36:14.957262

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "184a1c26dc16"
down_revision: Union[str, None] = "d74fcf8c0b1e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("stocks", sa.Column("market_cap", sa.Float(), nullable=True))
    op.add_column("stocks", sa.Column("pe_ratio", sa.Float(), nullable=True))
    op.drop_column("stocks", "date")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("stocks", sa.Column("date", sa.DATETIME(), nullable=True))
    op.drop_column("stocks", "pe_ratio")
    op.drop_column("stocks", "market_cap")
    # ### end Alembic commands ###
