"""Add missing date column to stocks

Revision ID: 1b5cda74336c
Revises: eea40ed64440
Create Date: 2024-09-28 23:37:41.604523

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "1b5cda74336c"
down_revision: Union[str, None] = "eea40ed64440"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
