"""Your migration message

Revision ID: 20324a418dfd
Revises: 3e4084e1e245
Create Date: 2024-09-23 17:57:57.718182

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "20324a418dfd"
down_revision: Union[str, None] = "3e4084e1e245"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
