"""Added missing columns

Revision ID: 8136cc14f577
Revises: 14f96da0ec16
Create Date: 2024-10-01 15:18:27.271149

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "8136cc14f577"
down_revision: Union[str, None] = "14f96da0ec16"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
