"""Recreate stocks table with correct columns

Revision ID: dc35511c4a5f
Revises: 1b5cda74336c
Create Date: 2024-09-28 23:41:55.437453

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "dc35511c4a5f"
down_revision: Union[str, None] = "1b5cda74336c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
