"""Add id column to stocks table

Revision ID: e3cab1a2d06b
Revises: 061d83894fa5
Create Date: 2024-10-13 01:14:07.310721

"""

from typing import Sequence, Union

# from alembic import op
# import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e3cab1a2d06b"
down_revision: Union[str, None] = "061d83894fa5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
