"""Add missing columns

Revision ID: eea40ed64440
Revises: 184a1c26dc16
Create Date: 2024-09-28 23:37:08.482961

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "eea40ed64440"
down_revision: Union[str, None] = "184a1c26dc16"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
