"""Add missing id column to stocks

Revision ID: fb225cc14cd2
Revises: 8136cc14f577
Create Date: 2024-10-01 19:40:27.516520

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fb225cc14cd2"
down_revision: Union[str, None] = "8136cc14f577"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
