name: Auto-Generate Branch for Issue

# on:
#   issues:
#     types: [opened]

on:
  workflow_dispatch:


jobs:
  create_branch:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Get issue details
      id: issue
      run: |
        echo "Issue number: ${{ github.event.issue.number }}"
        echo "Issue title: ${{ github.event.issue.title }}"
        echo "##[set-output name=number;]${{ github.event.issue.number }}"
        echo "##[set-output name=title;]${{ github.event.issue.title }}"

    - name: Format branch name
      id: format
      run: |
        # Capture issue number and title
        issue_number="${{ steps.issue.outputs.number }}"
        issue_title="${{ steps.issue.outputs.title }}"

        # Convert issue title to lowercase and replace spaces with hyphens
        formatted_title=$(echo "$issue_title" | tr '[:upper:]' '[:lower:]' | sed 's/ /-/g')

        # Limit the length of the formatted title to avoid excessively long branch names
        short_title=$(echo "$formatted_title" | cut -c 1-30)

        # Branch type, default to "feature" unless a bug label is present
        branch_type="feature"

        # Form the full branch name
        full_branch_name="${branch_type}/${issue_number}-${short_title}"

        echo "Generated branch name: $full_branch_name"
        echo "##[set-output name=branch_name;]$full_branch_name"

    - name: Create and push branch
      run: |
        branch_name="${{ steps.format.outputs.branch_name }}"

        # Create and push the new branch
        git checkout -b "$branch_name"
        git push origin "$branch_name"

    - name: Add comment to issue
      run: |
        branch_name="${{ steps.format.outputs.branch_name }}"

        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -X POST -d "{\"body\": \"Branch created: $branch_name\"}" \
          "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments"
