name: Auto-Generate Branch for Issue

on:
  issues:
    types: [opened]

jobs:
  create_branch:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Get issue details
      id: issue
      run: |
        echo "##[set-output name=number;]${{ github.event.issue.number }}"
        echo "##[set-output name=title;]${{ github.event.issue.title }}"

    - name: Create a branch from the issue
      run: |
        issue_number=${{ steps.issue.outputs.number }}
        issue_title=${{ steps.issue.outputs.title }}

        # Convert the issue title to lowercase and replace spaces with hyphens
        branch_name=$(echo "${issue_title}" | tr '[:upper:]' '[:lower:]' | sed 's/ /-/g')

        # Choose a branch type (e.g., feature or bugfix) based on label
        branch_type="feature"  # Modify this if needed based on your use case

        # Create the branch name with the issue number and short description
        full_branch_name="${branch_type}/${issue_number}-${branch_name}"

        # Checkout to the new branch
        git checkout -b "$full_branch_name"

        # Push the branch to the repository
        git push origin "$full_branch_name"

    - name: Add a comment on the issue with branch name
      run: |
        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        -X POST -d "{\"body\": \"Branch created: $full_branch_name\"}" \
        "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments"
