name: Validate Branch Name

on:
  push:
    branches:
      - '**'

jobs:
  check-branch-name:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get current branch name
      run: |
        echo "Branch name: ${{ github.ref }}"
        echo "${{ github.ref }}" | sed 's/refs\/heads\///g' > branch_name.txt

    - name: Validate branch name
      id: validate_branch_name
      run: |
        branch_name=$(cat branch_name.txt)
        regex="^(feature|bugfix|hotfix|fix)\/[0-9]+-[a-z0-9-]+$|^(master|main)$"  # Updated regex to include 'master' and 'main'
        if [[ ! "$branch_name" =~ $regex ]]; then
          echo "Invalid branch name '$branch_name'. Must follow 'type/issue-description' format or be 'master'/'main'."
          exit 1
        fi
      shell: bash
