name: Branch Name Check

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  branch_name_check:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Validate Branch Name
      run: |
        branch_name=$(echo "${GITHUB_REF#refs/heads/}")
        branch_regex="^(feature|bugfix|improvement|docs|hotfix)/[a-z0-9\-]+$"

        if ! [[ "$branch_name" =~ $branch_regex ]]; then
          echo "Error: Branch name '$branch_name' does not follow the naming convention."
          echo "Branch names must follow the format: <type>/<short-description>"
          echo "Examples: feature/add-stock-crud, bugfix/fix-db-error"
          exit 1
        fi
