name: Branch Name and Commit Message Check

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  branch_and_commit_check:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Validate Branch Name
      run: |
        branch_name=$(echo "${GITHUB_REF#refs/heads/}")
        
        # Skip branch validation for pull requests and certain branches
        if [[ "$GITHUB_REF" == refs/pull/* ]]; then
          echo "Skipping branch name check for pull requests."
          exit 0
        fi

        if [[ "$branch_name" == "master" || "$branch_name" == "main" ]]; then
          echo "Branch name '$branch_name' is excluded from validation."
          exit 0
        fi

        # Regex for valid branch names
        branch_regex='^(feature|bugfix|improvement|docs|hotfix)/[a-z0-9]+(-[a-z0-9]+)*$'

        if ! [[ "$branch_name" =~ $branch_regex ]]; then
          echo "Error: Branch name '$branch_name' does not follow the naming convention."
          echo "Branch names must follow the format: <type>/<short-description>"
          echo "Examples: feature/add-stock-crud, bugfix/fix-db-error"
          exit 1
        fi
