name: Verify DevContainer Integrity

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read  # Explicitly set permissions

jobs:
  verify-devcontainer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU (for multi-platform builds)
        uses: docker/setup-qemu-action@v2

      - name: Build DevContainer
        run: |
          docker build -f .devcontainer/Dockerfile -t devcontainer-test .

      - name: Verify DevContainer
        run: |
          docker run --rm devcontainer-test echo "DevContainer is working!"

      # TODO: its in progress, Uncomment and adjust the following steps if you want to validate the devcontainer.json
      # - name: Download DevContainer Schema Files
      #   run: |
      #     curl -o devContainer.schema.json https://raw.githubusercontent.com/devcontainers/spec/main/schemas/devContainer.schema.json
      #     curl -o devContainer.base.schema.json https://raw.githubusercontent.com/devcontainers/spec/main/schemas/devContainer.base.schema.json

      # - name: Validate DevContainer JSON Schema
      #   run: |
      #     docker run --rm -v $(pwd):/workspace devcontainer-test ajv validate -s /workspace/devContainer.schema.json -d /workspace/.devcontainer/devcontainer.json
