name: Flake8 Linting and Report

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install dependencies (flake8 and flake8-html)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 flake8-html

      # Step 4: Run flake8 with HTML report generation
      - name: Run flake8 and generate HTML report
        run: |
          mkdir -p flake8_report
          flake8 --format=html --htmldir=flake8_report --count --exit-zero > flake8_report/flake8_report.txt
          flake8 --statistics

      # Step 5: Upload the flake8 HTML report as an artifact
      - name: Upload flake8 HTML report
        uses: actions/upload-artifact@v3
        with:
          name: flake8-report
          path: flake8_report

      # Step 6: Set threshold for number of warnings (customizable)
      - name: Enforce Flake8 warnings threshold
        run: |
          max_warnings=20  # Customize this threshold value
          actual_warnings=$(flake8 --statistics --count | tail -n1 | awk '{print $1}')
          if [ "$actual_warnings" -gt "$max_warnings" ]; then
            echo "Too many warnings: $actual_warnings (threshold: $max_warnings)"
            exit 1
          else
            echo "Flake8 passed with $actual_warnings warnings (threshold: $max_warnings)"
          fi
