name: Run Tests with Coverage

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-xdist  # Install pytest-xdist for parallel testing

      - name: Run tests with coverage
        run: |
          pytest -n auto --cov=src --cov-fail-under=80 tests/
          coverage html  # Generate an HTML report
          coverage xml   # Generate an XML report for external tools

      - name: Upload coverage HTML report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-html-report
          path: htmlcov/  # Upload the HTML coverage report

      - name: Verify XML coverage file exists
        run: ls -la coverage.xml  # Check in the root directory

      - name: Upload coverage to GitHub
        uses: orgoro/coverage@v3.2
        with:
          coverageFile: coverage.xml  # Use the correct path for the XML report
          token: ${{ secrets.GITHUB_TOKEN }}
